// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace AnatUNIL
{
	public partial class AnswerCell : UITableViewCell
	{
		public AnswerCell (IntPtr handle) : base (handle)
		{
		}
	}
}
